### ISSUE TITLE
Cannot call methode 'forEach'

### ISSUE THREAD

**Issue by eyotiste** [KiLMaN/T411-Torznab#1]
Hi,
I got this error when trying to use your app

> Server listening on port 9876
> Got token :  undefined
> { url: 'http://api.t411.io/torrents/search/?offset=0&limit=100',
> headers: { Authorization: undefined } }
> Exception : TypeError: Cannot call method 'forEach' of undefined

**Comment by KiLMaN** [comment]
Did you change your T411 Credentials inside the server.js file ?

Replace 

```
var userName = "***";
var userPass = "***";
```

by your credentials

**Comment by eyotiste** [comment]
Oh, I'm stupid -_-

**Comment by KiLMaN** [comment]
I'v updated the server to separate the configuration file and exit if T411 doesn't give back the token (bad user/password)
It's a little bit more foolproof ;)
