### ISSUE TITLE
VFF et multi dans sonarr

### ISSUE THREAD

**Issue by KaylFr** [KiLMaN/T411-Torznab#10]
Bonjour,

Quand sonarr chercher des episodes , il ne prend pas ceux qui sont marquer "Multi (Francais inclu)", est ce que cela peut être contourné par le script de T411-Torznab ou il faut jouer avec sonarr ?

si quelqu'un a une solution

Merci d'avance

---

Hello,

When sonarr seek episodes, it does not take those marked "Multi (French included)," is that it can be bypassed by the T411-Torznab script or you have to play with sonarr?

if anyone has a solution

thank

Kayl

**Comment by KiLMaN** [comment]
Cela dépend de la configuration de sonarr. Le code qui détecte la langue ne prends pas en compte le texte "Multi(Français)" donc pour lui c'est de l'anglais. Et si tu demande que la série soit en français ça fonctionne pas.

**Comment by KaylFr** [comment]
Une technique/manipulation que cela soit prit en compte ?

**Comment by KiLMaN** [comment]
J'ai une version modifié de sonarr qui gère un peu mieux les versions françaises. Mais j'ai pas tester le Multi. 
Tu n'aurais pas la série sur laquelle tu test ?

**Comment by KaylFr** [comment]
sur "orange is the new black" la saison 1 en 1080p saison 1, pourrai je profiter de cette version modifier ?

Edit : Il ne trouve pas non plus the big bang theory saison 7, alors que celui ci est marquer français sur t411

**Comment by KiLMaN** [comment]
Je regarde ça quand j'ai un peu plus de temps. La version est sur mon github mais il faut la recompiler. (pas donné à tout le monde)

**Comment by KaylFr** [comment]
Avez vous eu le temp de regarder ? au passage merci d'avoir fait la mise a jour avec leur nouvelle adresse, sa fait plaisir que sa soit aussi suivi :)

**Comment by KiLMaN** [comment]
Malheureusement non, pour le moment je suis très chargé et j'ai peu de temps à consacrer à ce projet.

**Comment by KiLMaN** [comment]
Je suis actuellement en train de regarder, mais j'ai peur que si je fasse la modification, cela risque de poser certains problèmes car le fait que "Multi" veuille dire Français + Autre langues n'est pas le cas sur d'autres sites. Il ne faut donc pas que je modifie Sonarr pour prendre en compte ce cas.

Par contre je peux essayer une "rustine" pour que sonarr croie qu'il y ait le français.

**Comment by KaylFr** [comment]
Nous ne prenons que les series en VF donc j'ai pense modifier le script pour utiliser les recherche par term en lui disant soit VFF ou Multi (Francais) inclu (et pas quebecois) après est ce que tu serait d'accord si je partage les modification sur mon blog kayl.fr tous en créditant bien sur le script original

**Comment by KiLMaN** [comment]
Pas de soucis, tu peux même forker ce dépôt et je verrais pour peut être y intégrer tes modifications. 

Le 7 mars 2016 15:50, à 15:50, Kayl51 notifications@github.com a écrit:

**Comment by f-vt** [comment]
Pour le multi on peut mettre en anglais la série puis utiliser les restrictions qui sont dans les paramètres avancés des indexeurs avec les mots suivants : multi Multi MULTi multI multy vo+vf vo/vf vo.vf vovf vf+vo vf-vo vf/vo vfvo vf.vo vo-vf vo&vf vf&vo vo_vf vf_vo multilangue multilanguage multilangage multilingual
