### ISSUE TITLE
changement url t411

### ISSUE THREAD

**Issue by bidulle95** [KiLMaN/T411-Torznab#11]
bonjour je viens de voir que la T411 change url : http://www.t411.ch/
car il on été bloquer  
tu peut faire la modif stp

**Comment by foux** [comment]
J'ai fait la pullrequest #12 pour ce changement @KiLMaN. Tu peux l'intégrer? D'après le site l'ancienne URL ne marchera plus demain.

**Comment by KiLMaN** [comment]
fait
