### ISSUE TITLE
What about CouchPotato ?

### ISSUE THREAD

**Issue by blablanumerodeux** [KiLMaN/T411-Torznab#16]
Hello, 
Is it possible to make this thing work with CP ?
It would be so useful !
Thanks by advance,

**Comment by KiLMaN** [comment]
There is already a provider for couch potato on github. Check it out 

Le 8 mai 2016 16:06, à 16:06, blablanumerodeux notifications@github.com a écrit:

**Comment by blablanumerodeux** [comment]
Yes thank you, I found it.
