### ISSUE TITLE
Failed test Torznab

### ISSUE THREAD

**Issue by youngcesar** [KiLMaN/T411-Torznab#20]
Il me semble que depuis ce matin impossible de faire une recherche avec T411-Torznab via sonarr le test de connexion est en failed systématiquement.

je suis le seul peut être mais j'ai tout refais de a à z

**Comment by KiLMaN** [comment]
Quelle erreur avez vous ?

Le 20 oct. 2016, à 14:34, youngcesar <notifications@github.com<mailto:notifications@github.com>> a écrit:

Il me semble que depuis ce matin impossible de faire une recherche avec T411-Torznab via sonarr le test de connexion est en failed systématiquement.

je suis le seul peut être mais j'ai tout refais de a à z

**Comment by youngcesar** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/22958863/19562709/9f376698-96dd-11e6-8806-32500371cdad.jpg)

pourtant la commande node server.js see lance bien mais la connexion via sonarr non

**Comment by youngcesar** [comment]
#bonjour,

j'ai trouver c’était le port bloqué 9876 j'ai changé dans le json en 9877 et c'est passé.
