### ISSUE TITLE
Possibility to add automatic build on docker hub ?

### ISSUE THREAD

**Issue by lokiiiii** [KiLMaN/T411-Torznab#23]
Hello there,
I'm not sure that you're a french guy so I'll give a try in english :p 
Could it be possible for you to add an automatic build of your project on the docker hub ? So I can add your awesome project that I use every day simply in my docker-compose file ?
It would be awesome ! 
Thanks a lot (and bigger thanks for your project ! :) )

**Comment by Moubai** [comment]
already multiple docker file @ docker hub
https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=t411&starCount=0

**Comment by mcatapptic** [comment]
There are indeed some docker files with automatic build but none seems up to date. Could you point one or create an official ?

**Comment by huguesgr** [comment]
+1

**Comment by KiLMaN** [comment]
I don't use docker so I can't. But if anyone want to try.

**Comment by huguesgr** [comment]
Well since you own this repository, you are the only one who can create an **automated** build.
You just need to create an account on https://hub.docker.com/ and follow the steps to create one.

**Comment by KiLMaN** [comment]
Done 
https://hub.docker.com/r/kilman/t411-torznab/

**Comment by huguesgr** [comment]
Great! Thank you very much for the quick answer, I guess you can close this issue.
