### ISSUE TITLE
Error: Invalid octal number create mask

### ISSUE THREAD

**Issue by ErwanNumb** [KiLMaN/T411-Torznab#3]
I got this error when I try to launch the script. What can I do?

Thanks!

**Comment by KiLMaN** [comment]
Never seen that error before, can you post a screenshot or more informations ?

**Comment by ErwanNumb** [comment]
Yes sure

![unnamed 2](https://cloud.githubusercontent.com/assets/9214181/10219804/5c8f3052-6842-11e5-8fec-e3dcd2b631c7.png)

**Comment by KiLMaN** [comment]
Did you check the permission of the folder / files (chmod ? chown ?) 
Can you post the result of `ls -al` command inside the folder ?

**Comment by ErwanNumb** [comment]
Sure, here it is:

![screenshot_2015-10-01-16-44-57](https://cloud.githubusercontent.com/assets/9214181/10223967/0c899fec-685c-11e5-9993-240f97e10d00.png)

**Comment by KiLMaN** [comment]
I hope your running `node server.js` as root, with what you send me, i don't know why this isn't working for you ... 
Have you tried to run another nodejs program ? 
Make sure that you run `npm install` to install all the dependencies required. 
Honestly i have no idea why you have such an error, here is my configuration and it's running just fine
![image](https://cloud.githubusercontent.com/assets/1059727/10225198/e997459c-6861-11e5-9e62-4035a0dcc006.png)

**Comment by ErwanNumb** [comment]
Yes I'm running as root.
I'll try to investigate, thank you anyway!

**Comment by KiLMaN** [comment]
Just to be sure, what OS are you running on ?

**Comment by ErwanNumb** [comment]
I'm running DSM 5.x (xpenology) on a HP proliant server

**Comment by KiLMaN** [comment]
On second thought, try changing the permissions of all files : `chmod 755 ./* -R` and see if it changes anything
It seems like this error is tied to the permissions and `rwxrwxrwx` for each file doesn't seems right ...

**Comment by KiLMaN** [comment]
Any update on your problem ?
