### ISSUE TITLE
Radarr support

### ISSUE THREAD

**Issue by obouallou** [KiLMaN/T411-Torznab#32]
The torznab api impelmented for T411 doesn't support movie search.
can you please add support for t=movie ?

Thank you !

**Comment by KiLMaN** [comment]
It could be added quite easily.
I'll try to work on it this week.

**Comment by obouallou** [comment]
Merci ! ;)

**Comment by galli-leo** [comment]
Also could you add searching movies by imdbid? Else we have to use the search query, which can be unreliable.

**Comment by PastaGringo** [comment]
Thanks @KiLMaN

**Comment by KiLMaN** [comment]
@galli-leo As T411 doesn't support searching with the imdbID, my software must convert it to the movie title. I'm currently working on it, but there is not much i can do about it.

**Comment by galli-leo** [comment]
@KiLMaN Gotcha, then you can leave the imdbid out. We will just use a normal search query. Did you ask the admins of t411 yet, if they will add support for that?

**Comment by KiLMaN** [comment]
@galli-leo I didn't ask them and i think they wont add this because the users will have to add when they upload the file and it will be quite cubbersome. 
I've just finished the update to support it, To update please make a 
`git pull`
and
`npn install` to install the dependencies

**Comment by PastaGringo** [comment]
It's working ! 👍 :1st_place_medal: 
Thanks for your help guys @KiLMaN @galli-leo
