### ISSUE TITLE
Missing results / manually verified

### ISSUE THREAD

**Issue by MIKAd3v** [KiLMaN/T411-Torznab#4]
Hello,

First, thank you for your great script.

It works pretty well, but I'm experiencing an issue: it seems that it's dropping some results when querying some releases on Sonaar.

For example, I'm trying to searching one specific release of "Gintama 291", so I've manually entered the following url: "http://<"HOST-HERE">:9876/api?t=search&extended=0&apikey=<"APIKEYHERE">&offset=0&limit=100&q=gintama+291".

Here is the result:
![image](https://cloud.githubusercontent.com/assets/4604296/11918666/d2bfbc24-a73a-11e5-992a-73ef61867cb6.png)

But one release is missing.

I've manually tried with another torznab script (Jackett-public - not working on Sonaar) and here are the url + results:
"http://<"HOSTHERE">:9117/torznab/t411/api?t=tvsearch&extended=1&apikey=<"APIKEYHERE">&offset=0&limit=100&q=gintama+291"

![image](https://cloud.githubusercontent.com/assets/4604296/11918684/c40eb4c2-a73b-11e5-87fb-5deff9810e82.png)

As you can see, another result is returned (which is the one I always wanted for the beginning).

Could you help me about it?
Thank you.

**Comment by KiLMaN** [comment]
Hi. The strange thing is that they number of items  should be 2 as shown in the tag torznab:response.  I will look at it when I have time. 
Thank you

**Comment by KiLMaN** [comment]
I've found the reason why.
The torrent you searching is not yet approved. By default my proxy doesn't let you download it. If you want to have all torrent even the ones that are not approved you should change your configuration file and change `"onlyVerified":true` to `"onlyVerified":false`
