### ISSUE TITLE
Error : 301

### ISSUE THREAD

**Issue by toshi24** [KiLMaN/T411-Torznab#40]
Hello,
I have just installed your code on Docker (syno DS415+) and I have the following error in the log : 
`Response from T411 invalid. Error : 301`
Do you know what it mean ?
I already chech the password and login many time and the T411 website adress is correct in ''server'' file.

**Comment by FarLight83** [comment]
Hello,
Mine has been working well for 1 year.
But T411 changes url a few days ago and now it has problems.
It may be just wait

**Comment by foux** [comment]
T411 api is currently down, that's why it's not working.

**Comment by ninuxio** [comment]
Hello everyone,

@foux did you check https://t411.xyz ? dont know if this is trustable

**Comment by dadadounee** [comment]
Hi ! 

I don't know if this is relevant but i can see that api.t411.ai is https now....
was it before ?

**Comment by PastaGringo** [comment]
Same error "error: Response from T411 invalid. Error : 301"

**Comment by ghost** [comment]
Yes I think they force http request to https now It may be relevant.

**Comment by foux** [comment]
The t411 API is down, it has nothing to do with HTTPS right now (you've got another error if you switch to HTTPS). 

All we have to do is wait for the API to be fixed before seeing if anything else needs to be changed

**Comment by ghost** [comment]
Alright :/

**Comment by KiLMaN** [comment]
Still waiting. 
If you have any information please update the ticket so I can test quickly. 
Thanks

**Comment by clem73** [comment]
Any news?
For me it still does not work.

**Comment by KiLMaN** [comment]
No news. When I have time I will change the proxy to a scrapper that can use the website instead of the api.

**Comment by ChibiTomo** [comment]
You can know if the API is back [HERE](http://irc.t411.ai/screens/ms/tutoriels/Nathann83/ip_t411.php).
For the scrapper, look at this [cardigann definition](https://github.com/cardigann/cardigann/blob/master/definitions/t411.yml), I think  it can help for starting.

**Comment by foux** [comment]
@KiLMaN is it really necessary? We already have cardigann that does this. The whole point of your software is, in fact, that it is using the API, way more precise that just scraping the website.

**Comment by ghost** [comment]
Oh my god Api is working !

**Comment by clem73** [comment]
I tried with https, and it still does not work.
Is it working for you ?

**Comment by ghost** [comment]
Are you sure you changed the api url to https in server.js
I made a pull request here https://github.com/KiLMaN/T411-Torznab/pull/42
And yes it's working like a charm.

**Comment by clem73** [comment]
Yes I saw your pull request and made the modification.
But it does not work. Is there anyone else who try this too?

edit : It works ! I must redo npm install, and it is ok, module imdb was missing.
But as I run the server.js with forever, I don't see the error message.
Thanks

**Comment by ninuxio** [comment]
hi all

- 1. change http to https for the api var in server.js
- 2. docker build
- 3. docker run with the new image

**Comment by toshi24** [comment]
It work for me, thanks !

2017-04-13 19:20 GMT+02:00 Nicolas <notifications@github.com>:

**Comment by KiLMaN** [comment]
Fixed in the last commit.
