### ISSUE TITLE
Search show all results of a tv show

### ISSUE THREAD

**Issue by ghost** [KiLMaN/T411-Torznab#6]
Hello,

I'm using this awesome proxy for several month with Sonaar and recently I got an issue,

When I manually search for a tv show episode, Sonaar show me all the episodes of this tv show instead of the one I was looking for.

I tried with an other indexer and it's working fine. Maybe the t411 search API has been updead recently?

Thanks,

**Comment by KiLMaN** [comment]
I've seen this before. The T411 api doesn't filter the results like before. 
I must update my software to do so. It still in development. 
I will be updating it soon.

**Comment by ghost** [comment]
Perfect thanks for this quick update :)

**Comment by foux** [comment]
Hi.
Just start noticing this recently too. Will love to know when you have news on this ;)

**Comment by KiLMaN** [comment]
I'm working on it. I hope to fix this by the end of the week.

**Comment by foux** [comment]
That’s great news! Good luck

**Comment by KiLMaN** [comment]
It should be working again (don't forget to do `npm install` after updating git with `git pull`)

**Comment by ghost** [comment]
I confirm it's working now :+1: 

And BTW I like the new more detailled log files.
