### ISSUE TITLE
Sonarr : Getting release form indexer failed

### ISSUE THREAD

**Issue by BadFlo** [KiLMaN/T411-Torznab#7]
HI,

My Sonarr can't get the release from the indexer. It says:
"Getting release form indexer failed"

Any chack I can do ? I am running this in a docker and rebuilt it totally already.

Please advise,

**Comment by BadFlo** [comment]
Here is the log from Sonarr:

 ReleaseModule Downloading torrent failed: Downloading torrent failed 14:11 
 RTorrent Downloading torrent file for episode 'The.Big.Bang.Theory.S09E11.VOSTFR.720p.WEB-DL.DD5.1.H264-ARK01' failed (http://127.0.0.1:12345/torrent/5434282): Error: ConnectFailure (Connection refused) 14:11 
 ReleaseModule Downloading torrent failed: Downloading torrent failed 14:11 
 RTorrent Downloading torrent file for episode 'The.Big.Bang.Theory.S09E11.VOSTFR.720p.WEB-DL.DD5.1.H264-ARK01' failed (http://127.0.0.1:12345/torrent/5434282): Error: ConnectFailure (Connection refused) 14:11

**Comment by KiLMaN** [comment]
Any log from the proxy? 
I can download without problems this torrent. What is the topology? Running the proxy and sonnar in the same host? Using a proxy like apache in front of  it? 
It's probably a problem with the url of the torrent if he can't detect that he is behind a apache proxy. The link will be erroneous

**Comment by BadFlo** [comment]
T411-Torznab is running on another host. Sonarr is Getting access to the torznab via http://T411:12345. Getting the list of torrents is ok. But when it tries to download them, I think it try to get the torrent from localhost instead of T411 host ...

**Comment by KiLMaN** [comment]
It's what I though. What are you using to redirect T411 to the right host?

**Comment by KiLMaN** [comment]
It's what I though. What are you using to redirect T411 to the right host?

**Comment by BadFlo** [comment]
Nothing, Sonar just grabs T411 from my local DNS to use the correct IP.
I tried with the IP directly, with no change.

**Comment by KiLMaN** [comment]
It should be ok now.
